// Generated by CoffeeScript 1.6.3
var app;

app = angular.module('wowRealmStatus', []);

app.factory('Realms', function($http) {
  return function(cb) {
    var url;
    url = "http://us.battle.net/api/wow/realm/status?jsonp=JSON_CALLBACK";
    return $http.jsonp(url).success(function(json) {
      return cb(json.realms);
    });
  };
});

app.filter('realmType', function() {
  return function(type) {
    switch (type) {
      case 'pve':
        return "PvE";
      case 'pvp':
        return "PvP";
      case 'rp':
        return "RP";
      case 'rppvp':
        return "RP PvP";
    }
  };
});

app.filter('capitalize', function() {
  return function(str) {
    if (str) {
      return str[0].toUpperCase() + str.slice(1).toLowerCase();
    } else {
      return "";
    }
  };
});

app.filter('boolToString', function() {
  return function(boolean, trueString, falseString) {
    if (boolean) {
      return trueString;
    } else {
      return falseString;
    }
  };
});

app.factory('hashChange', function($window) {
  return function(listener) {
    return window.onhashchange = function() {};
  };
});

app.controller('RealmsController', function($scope, $rootScope, $timeout, Realms) {
  var refresh, _ref, _ref1;
  $scope.lastUpdate = null;
  $scope.realms = [];
  $scope.search = (_ref = (_ref1 = location.hash) != null ? _ref1.substr(1) : void 0) != null ? _ref : '';
  window.onhashchange = function() {
    return $scope.$apply(function() {
      var _ref2, _ref3;
      return $scope.search = (_ref2 = (_ref3 = location.hash) != null ? _ref3.substr(1) : void 0) != null ? _ref2 : '';
    });
  };
  $scope.$watch('search', function(val) {
    if (val != null) {
      return location.hash = val;
    }
  });
  refresh = function() {
    $scope.loading = true;
    return Realms(function(realms) {
      $scope.realms = realms;
      $scope.loading = false;
      $scope.lastUpdate = new Date();
      return $timeout(refresh, 60 * 5 * 1000);
    });
  };
  return refresh();
});
