// Generated by CoffeeScript 1.4.0
var app;

app = angular.module('wowRealmStatus', []);

app.factory('Realms', function($http) {
  return function(cb) {
    var url;
    url = "http://us.battle.net/api/wow/realm/status?jsonp=JSON_CALLBACK";
    return $http.jsonp(url).success(cb);
  };
});

app.filter('realmType', function() {
  return function(type) {
    switch (type) {
      case 'pve':
        return "PvE";
      case 'pvp':
        return "PvP";
      case 'rp':
        return "RP";
      case 'rppvp':
        return "RP PvP";
    }
  };
});

app.filter('realmStatus', function() {
  return function(status) {
    if (status) {
      return "Up";
    } else {
      return "Down";
    }
  };
});

app.filter('realmPop', function() {
  return function(pop) {
    switch (pop) {
      case 'low':
        return "Low";
      case 'medium':
        return "Medium";
      case 'high':
        return "High";
      default:
        return pop;
    }
  };
});

app.filter('realmQueue', function() {
  return function(queue) {
    if (queue) {
      return "Yes";
    } else {
      return "No";
    }
  };
});

app.controller('RealmController', function($scope, $timeout, Realms) {
  var refresh, _ref, _ref1;
  $scope.search = (_ref = (_ref1 = location.hash) != null ? _ref1.substr(1) : void 0) != null ? _ref : '';
  $scope.lastUpdate = null;
  $scope.realms = [];
  window.onhashchange = function() {
    return $scope.search = location.hash;
  };
  $scope.$watch('search', function(val) {
    if (val != null) {
      return location.hash = val;
    }
  });
  $scope.showAll = function() {
    return $scope.search = '';
  };
  $scope.showOnly = function(name) {
    return $scope.search = name;
  };
  refresh = function() {
    $scope.loading = true;
    return Realms(function(data) {
      $scope.realms = data.realms;
      $scope.loading = false;
      $scope.lastUpdate = new Date();
      return $timeout(refresh, 60 * 5 * 1000);
    });
  };
  return refresh();
});
